"""verify 2.0 syntax 2

Revision ID: c85c4d1f30f3
Revises: 36a059823211
Create Date: 2026-09-02 23:04:14.560625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c85c4d1f30f3'
down_revision: Union[str, None] = '36a059823211'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('discounts', 'discount_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('discounts', 'discount_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
